import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";

type JsonObject = Record<string, unknown>;

type SourceToken = {
	cssVariable?: string;
	value?: unknown;
	role?: unknown;
	source?: unknown;
	hex?: unknown;
	name?: unknown;
	description?: unknown;
	category?: unknown;
};

type CompiledToken = {
	key: string;
	cssVariable?: string;
	value: string;
	role?: string;
	source?: string;
	hex?: string;
	name?: string;
	description?: string;
	category?: string;
};

const CATEGORY_NAMES = [
	"colors",
	"spacing",
	"radii",
	"motion",
	"typography",
	"shadows",
	"focus",
	"breakpoints",
	"brandMark",
] as const;

const REPO_ROOT = resolve(import.meta.dir, "../../../../..");
const SOURCE_PATH = resolve(
	REPO_ROOT,
	"projects/vecreal/drafts/brand-atoms/design-tokens.json",
);
const OUTPUT_PATH = resolve(
	REPO_ROOT,
	"vendor/superset-sh/apps/desktop/src/renderer/components/vecreal/tokens.ts",
);

function isObject(value: unknown): value is JsonObject {
	return typeof value === "object" && value !== null && !Array.isArray(value);
}

function stringify(value: unknown): string | undefined {
	if (typeof value === "string") {
		return value;
	}
	if (typeof value === "number" || typeof value === "boolean") {
		return String(value);
	}
	return undefined;
}

function compileToken(key: string, value: SourceToken): CompiledToken | null {
	const tokenValue = stringify(value.value);

	if (!tokenValue) {
		return null;
	}

	const token: CompiledToken = {
		key,
		value: tokenValue,
	};

	const cssVariable = stringify(value.cssVariable);
	if (cssVariable) {
		token.cssVariable = cssVariable;
	}

	const role = stringify(value.role);
	if (role) {
		token.role = role;
	}

	const source = stringify(value.source);
	if (source) {
		token.source = source;
	}

	const hex = stringify(value.hex);
	if (hex) {
		token.hex = hex;
	}

	const name = stringify(value.name);
	if (name) {
		token.name = name;
	}

	const description = stringify(value.description);
	if (description) {
		token.description = description;
	}

	const category = stringify(value.category);
	if (category) {
		token.category = category;
	}

	return token;
}

function compileCategory(source: unknown): Record<string, CompiledToken> {
	if (!isObject(source)) {
		return {};
	}

	const compiled: Record<string, CompiledToken> = {};

	for (const [key, value] of Object.entries(source)) {
		if (!isObject(value)) {
			continue;
		}

		const token = compileToken(key, value);
		if (token) {
			compiled[key] = token;
		}
	}

	return compiled;
}

function compileLockedVariables(source: unknown): CompiledToken[] {
	if (!Array.isArray(source)) {
		return [];
	}

	return source.flatMap((value) => {
		if (!isObject(value)) {
			return [];
		}

		const cssVariable = stringify(value.cssVariable);
		const fallbackKey = cssVariable?.replace(/^--/, "");
		const key = stringify(value.key) ?? fallbackKey;

		if (!key) {
			return [];
		}

		const token = compileToken(key, value);
		return token ? [token] : [];
	});
}

function mergeFromLocked(
	locked: CompiledToken[],
	categoryName: string,
	explicit: Record<string, CompiledToken>,
): Record<string, CompiledToken> {
	if (Object.keys(explicit).length > 0) {
		return explicit;
	}

	const fromLocked: Record<string, CompiledToken> = {};

	for (const token of locked) {
		if (token.category === categoryName) {
			fromLocked[token.key] = token;
		}
	}

	return fromLocked;
}

function emitExport(name: string, value: unknown, suffix = ""): string {
	return `export const ${name} = ${JSON.stringify(value, null, "\t")} as const${suffix};`;
}

const raw = await readFile(SOURCE_PATH, "utf8");
const source = JSON.parse(raw) as JsonObject;
const lockedRootVariables = compileLockedVariables(source.lockedRootVariables);

const categories = Object.fromEntries(
	CATEGORY_NAMES.map((name) => [
		name,
		mergeFromLocked(lockedRootVariables, name, compileCategory(source[name])),
	]),
);

const generated = [
	"/*",
	" * AUTO-GENERATED by scripts/compile-tokens.ts.",
	" * Source: projects/vecreal/drafts/brand-atoms/design-tokens.json.",
	" * Do not hand-edit; run `bun run compile:tokens` from apps/desktop.",
	" */",
	"",
	"export type CssVariableName = `--${string}`;",
	"",
	"export interface TokenEntry {",
	"\tkey: string;",
	"\tcssVariable?: CssVariableName;",
	"\tvalue: string;",
	"\trole?: string;",
	"\tsource?: string;",
	"\thex?: string;",
	"\tname?: string;",
	"\tdescription?: string;",
	"\tcategory?: string;",
	"}",
	"",
	emitExport("tokenMetadata", source.meta ?? {}),
	"",
	emitExport("colorTokens", categories.colors, " satisfies Record<string, TokenEntry>"),
	"",
	emitExport("spacingTokens", categories.spacing, " satisfies Record<string, TokenEntry>"),
	"",
	emitExport("radiusTokens", categories.radii, " satisfies Record<string, TokenEntry>"),
	"",
	emitExport("motionTokens", categories.motion, " satisfies Record<string, TokenEntry>"),
	"",
	emitExport("typographyTokens", categories.typography, " satisfies Record<string, TokenEntry>"),
	"",
	emitExport("shadowTokens", categories.shadows, " satisfies Record<string, TokenEntry>"),
	"",
	emitExport("focusTokens", categories.focus, " satisfies Record<string, TokenEntry>"),
	"",
	emitExport("breakpointTokens", categories.breakpoints, " satisfies Record<string, TokenEntry>"),
	"",
	emitExport("brandMarkTokens", categories.brandMark, " satisfies Record<string, TokenEntry>"),
	"",
	emitExport("lockedRootVariables", lockedRootVariables, " satisfies readonly TokenEntry[]"),
	"",
	"export const vecrealTokens = {",
	"\tmeta: tokenMetadata,",
	"\tcolors: colorTokens,",
	"\tspacing: spacingTokens,",
	"\tradii: radiusTokens,",
	"\tmotion: motionTokens,",
	"\ttypography: typographyTokens,",
	"\tshadows: shadowTokens,",
	"\tfocus: focusTokens,",
	"\tbreakpoints: breakpointTokens,",
	"\tbrandMark: brandMarkTokens,",
	"\tlockedRootVariables,",
	"} as const;",
	"",
	"export type VecrealTokens = typeof vecrealTokens;",
	"",
].join("\n");

await mkdir(dirname(OUTPUT_PATH), { recursive: true });
await writeFile(OUTPUT_PATH, generated, "utf8");

console.log(`Compiled Vecreal tokens to ${OUTPUT_PATH}`);
