/*
 * AUTO-GENERATED by scripts/compile-tokens.ts.
 * Source: projects/vecreal/drafts/brand-atoms/design-tokens.json.
 * Do not hand-edit; run `bun run compile:tokens` from apps/desktop.
 */

export type CssVariableName = `--${string}`;

export interface TokenEntry {
	key: string;
	cssVariable?: CssVariableName;
	value: string;
	role?: string;
	source?: string;
	hex?: string;
	name?: string;
	description?: string;
	category?: string;
}

export const tokenMetadata = {
	"name": "Vecreal brand atoms design tokens",
	"status": "draft extraction from locked HTML reference",
	"generatedFrom": "reference-design-system.html",
	"generatedOn": "2026-05-03",
	"canonicalVisualReference": "reference-design-system.html",
	"extractionNotes": [
		"CSS variables come from the first locked :root block in the HTML head.",
		"Breakpoints are documented in the HTML and extracted from section 22 because they are comments in :root, not active CSS declarations.",
		"Typography scale comes from section 05 because font classes are documented there, not as :root CSS variables.",
		"Section 59 (P-14) and Section 63 (P-13) added 2026-05-03; loop/anim entries documented under motion."
	],
	"sources": [
		"CSS :root locked token block, lines 12-104",
		"section 04 — Color",
		"section 05 — Typography",
		"section 22 — Foundations",
		"section 23 — Iconography",
		"section 48 — Cross-cutting",
		"section 59 — Approval workflow (P-14 motion, locked 2026-05-03)",
		"section 63 — Loading micro-indicators (locked 2026-05-03)"
	]
} as const;

export const colorTokens = {
	"bg-app-light": {
		"key": "bg-app-light",
		"value": "#FAFAF8",
		"cssVariable": "--bg-app-light",
		"source": "section 04 — Color; CSS :root locked token block",
		"hex": "#FAFAF8"
	},
	"bg-card-light": {
		"key": "bg-card-light",
		"value": "#FFFFFF",
		"cssVariable": "--bg-card-light",
		"source": "section 04 — Color; CSS :root locked token block",
		"hex": "#FFFFFF"
	},
	"bg-card-light-bottom": {
		"key": "bg-card-light-bottom",
		"value": "#FBFAF7",
		"cssVariable": "--bg-card-light-bottom",
		"role": "card gradient bottom on light",
		"source": "section 04 — Color; CSS :root locked token block",
		"hex": "#FBFAF7"
	},
	"bg-soft-light": {
		"key": "bg-soft-light",
		"value": "#F4F4F1",
		"cssVariable": "--bg-soft-light",
		"source": "section 04 — Color; CSS :root locked token block",
		"hex": "#F4F4F1"
	},
	"bg-hover-light": {
		"key": "bg-hover-light",
		"value": "#EFEFEC",
		"cssVariable": "--bg-hover-light",
		"source": "section 04 — Color; CSS :root locked token block",
		"hex": "#EFEFEC"
	},
	"border-light": {
		"key": "border-light",
		"value": "#E8E6E0",
		"cssVariable": "--border-light",
		"source": "section 04 — Color; CSS :root locked token block",
		"hex": "#E8E6E0"
	},
	"border-light-subtle": {
		"key": "border-light-subtle",
		"value": "#F0EEE8",
		"cssVariable": "--border-light-subtle",
		"source": "section 04 — Color; CSS :root locked token block",
		"hex": "#F0EEE8"
	},
	"border-light-strong": {
		"key": "border-light-strong",
		"value": "#D6D3CB",
		"cssVariable": "--border-light-strong",
		"role": "=== Surfaces (dark) ===",
		"source": "section 04 — Color; CSS :root locked token block",
		"hex": "#D6D3CB"
	},
	"bg-sidebar-dark": {
		"key": "bg-sidebar-dark",
		"value": "#0a0b0d",
		"cssVariable": "--bg-sidebar-dark",
		"role": "always-dark sidebar (both modes)",
		"source": "section 04 — Color; CSS :root locked token block",
		"hex": "#0a0b0d"
	},
	"bg-app-dark": {
		"key": "bg-app-dark",
		"value": "#131517",
		"cssVariable": "--bg-app-dark",
		"role": "main bg / app surface (dark mode)",
		"source": "section 04 — Color; CSS :root locked token block",
		"hex": "#131517"
	},
	"bg-card-dark-top": {
		"key": "bg-card-dark-top",
		"value": "#21242a",
		"cssVariable": "--bg-card-dark-top",
		"role": "card gradient top",
		"source": "section 04 — Color; CSS :root locked token block",
		"hex": "#21242a"
	},
	"bg-card-dark-bottom": {
		"key": "bg-card-dark-bottom",
		"value": "#1c1e23",
		"cssVariable": "--bg-card-dark-bottom",
		"role": "card gradient bottom",
		"source": "section 04 — Color; CSS :root locked token block",
		"hex": "#1c1e23"
	},
	"bg-pill-dark": {
		"key": "bg-pill-dark",
		"value": "#1f2126",
		"cssVariable": "--bg-pill-dark",
		"role": "topbar pill, secondary surfaces",
		"source": "section 04 — Color; CSS :root locked token block",
		"hex": "#1f2126"
	},
	"bg-cta-dark": {
		"key": "bg-cta-dark",
		"value": "#1F1D1A",
		"cssVariable": "--bg-cta-dark",
		"role": "primary CTA bubble (warm black, locked)",
		"source": "section 04 — Color; CSS :root locked token block",
		"hex": "#1F1D1A"
	},
	"border-dark": {
		"key": "border-dark",
		"value": "#2d2f36",
		"cssVariable": "--border-dark",
		"role": "card borders, subtle dividers",
		"source": "section 04 — Color; CSS :root locked token block",
		"hex": "#2d2f36"
	},
	"border-dark-subtle": {
		"key": "border-dark-subtle",
		"value": "#1d1f24",
		"cssVariable": "--border-dark-subtle",
		"role": "deepest separators",
		"source": "section 04 — Color; CSS :root locked token block",
		"hex": "#1d1f24"
	},
	"text-light-primary": {
		"key": "text-light-primary",
		"value": "#1F1D1A",
		"cssVariable": "--text-light-primary",
		"role": "headings, body emphasis",
		"source": "section 04 — Color; CSS :root locked token block",
		"hex": "#1F1D1A"
	},
	"text-light-secondary": {
		"key": "text-light-secondary",
		"value": "#5A5550",
		"cssVariable": "--text-light-secondary",
		"role": "body text",
		"source": "section 04 — Color; CSS :root locked token block",
		"hex": "#5A5550"
	},
	"text-light-tertiary": {
		"key": "text-light-tertiary",
		"value": "#918A82",
		"cssVariable": "--text-light-tertiary",
		"role": "meta, timestamps",
		"source": "section 04 — Color; CSS :root locked token block",
		"hex": "#918A82"
	},
	"text-light-disabled": {
		"key": "text-light-disabled",
		"value": "#B8B2A8",
		"cssVariable": "--text-light-disabled",
		"role": "dividers, separator chars",
		"source": "section 04 — Color; CSS :root locked token block",
		"hex": "#B8B2A8"
	},
	"text-dark-primary": {
		"key": "text-dark-primary",
		"value": "#f7f8f8",
		"cssVariable": "--text-dark-primary",
		"role": "LOCKED soft off-white. Headings, eyebrow flagged, wordmark.",
		"source": "section 04 — Color; CSS :root locked token block",
		"hex": "#f7f8f8"
	},
	"text-dark-body": {
		"key": "text-dark-body",
		"value": "#d0d6e0",
		"cssVariable": "--text-dark-body",
		"role": "body text, action row titles",
		"source": "section 04 — Color; CSS :root locked token block",
		"hex": "#d0d6e0"
	},
	"text-dark-muted": {
		"key": "text-dark-muted",
		"value": "#9097a1",
		"cssVariable": "--text-dark-muted",
		"role": "eyebrow type label, action row details",
		"source": "section 04 — Color; CSS :root locked token block",
		"hex": "#9097a1"
	},
	"text-dark-tertiary": {
		"key": "text-dark-tertiary",
		"value": "#62666d",
		"cssVariable": "--text-dark-tertiary",
		"role": "section labels, meta, dividers",
		"source": "section 04 — Color; CSS :root locked token block",
		"hex": "#62666d"
	},
	"text-dark-disabled": {
		"key": "text-dark-disabled",
		"value": "#5a5e66",
		"cssVariable": "--text-dark-disabled",
		"role": "disabled buttons, placeholder",
		"source": "section 04 — Color; CSS :root locked token block",
		"hex": "#5a5e66"
	},
	"clay-light": {
		"key": "clay-light",
		"value": "#A05847",
		"cssVariable": "--clay-light",
		"role": "LOCKED primary on light surfaces (wordmark, references, chrome)",
		"source": "section 04 — Color; CSS :root locked token block",
		"hex": "#A05847"
	},
	"clay-bright": {
		"key": "clay-bright",
		"value": "#C68070",
		"cssVariable": "--clay-bright",
		"role": "LOCKED primary on dark surfaces",
		"source": "section 04 — Color; CSS :root locked token block",
		"hex": "#C68070"
	},
	"clay": {
		"key": "clay",
		"value": "#7A3D32",
		"cssVariable": "--clay",
		"role": "deep brand accent for high-emphasis",
		"source": "section 04 — Color; CSS :root locked token block",
		"hex": "#7A3D32"
	},
	"clay-dark": {
		"key": "clay-dark",
		"value": "#5C2D26",
		"cssVariable": "--clay-dark",
		"role": "hover/depth for clay-family",
		"source": "section 04 — Color; CSS :root locked token block",
		"hex": "#5C2D26"
	},
	"success": {
		"key": "success",
		"value": "#5DA17D",
		"cssVariable": "--success",
		"role": "live indicator, confidence high, success states",
		"source": "section 04 — Color; CSS :root locked token block",
		"hex": "#5DA17D"
	},
	"success-dark": {
		"key": "success-dark",
		"value": "#4a8a68",
		"cssVariable": "--success-dark",
		"role": "gradient toned-down variant",
		"source": "section 04 — Color; CSS :root locked token block",
		"hex": "#4a8a68"
	},
	"warning-light": {
		"key": "warning-light",
		"value": "#A87A2E",
		"cssVariable": "--warning-light",
		"role": "flagged status on light surface",
		"source": "section 04 — Color; CSS :root locked token block",
		"hex": "#A87A2E"
	},
	"warning-dark": {
		"key": "warning-dark",
		"value": "#d4a960",
		"cssVariable": "--warning-dark",
		"role": "flagged status on dark surface",
		"source": "section 04 — Color; CSS :root locked token block",
		"hex": "#d4a960"
	},
	"error": {
		"key": "error",
		"value": "#c95151",
		"cssVariable": "--error",
		"role": "high priority, overdue, error states",
		"source": "section 04 — Color; CSS :root locked token block",
		"hex": "#c95151"
	},
	"error-dark": {
		"key": "error-dark",
		"value": "#B53D3D",
		"cssVariable": "--error-dark",
		"role": "darker error for emphasis",
		"source": "section 04 — Color; CSS :root locked token block",
		"hex": "#B53D3D"
	},
	"info": {
		"key": "info",
		"value": "#5A6878",
		"cssVariable": "--info",
		"role": "muted slate for info banners",
		"source": "section 04 — Color; CSS :root locked token block",
		"hex": "#5A6878"
	}
} as const satisfies Record<string, TokenEntry>;

export const spacingTokens = {
	"sp-0": {
		"key": "sp-0",
		"value": "0px",
		"cssVariable": "--sp-0",
		"role": "reset",
		"source": "section 22 — Foundations; CSS :root locked token block"
	},
	"sp-1": {
		"key": "sp-1",
		"value": "2px",
		"cssVariable": "--sp-1",
		"role": "hairline",
		"source": "section 22 — Foundations; CSS :root locked token block"
	},
	"sp-2": {
		"key": "sp-2",
		"value": "4px",
		"cssVariable": "--sp-2",
		"role": "tight inline",
		"source": "section 22 — Foundations; CSS :root locked token block"
	},
	"sp-3": {
		"key": "sp-3",
		"value": "6px",
		"cssVariable": "--sp-3",
		"role": "compact",
		"source": "section 22 — Foundations; CSS :root locked token block"
	},
	"sp-4": {
		"key": "sp-4",
		"value": "8px",
		"cssVariable": "--sp-4",
		"role": "default inline",
		"source": "section 22 — Foundations; CSS :root locked token block"
	},
	"sp-5": {
		"key": "sp-5",
		"value": "10px",
		"cssVariable": "--sp-5",
		"role": "row spacing",
		"source": "section 22 — Foundations; CSS :root locked token block"
	},
	"sp-6": {
		"key": "sp-6",
		"value": "12px",
		"cssVariable": "--sp-6",
		"role": "card-to-row gap",
		"source": "section 22 — Foundations; CSS :root locked token block"
	},
	"sp-7": {
		"key": "sp-7",
		"value": "14px",
		"cssVariable": "--sp-7",
		"role": "compact card pad",
		"source": "section 22 — Foundations; CSS :root locked token block"
	},
	"sp-8": {
		"key": "sp-8",
		"value": "16px",
		"cssVariable": "--sp-8",
		"role": "standard card pad",
		"source": "section 22 — Foundations; CSS :root locked token block"
	},
	"sp-9": {
		"key": "sp-9",
		"value": "20px",
		"cssVariable": "--sp-9",
		"role": "loose card pad",
		"source": "section 22 — Foundations; CSS :root locked token block"
	},
	"sp-10": {
		"key": "sp-10",
		"value": "24px",
		"cssVariable": "--sp-10",
		"role": "section inner / page-x",
		"source": "section 22 — Foundations; CSS :root locked token block"
	},
	"sp-11": {
		"key": "sp-11",
		"value": "32px",
		"cssVariable": "--sp-11",
		"role": "subsection break",
		"source": "section 22 — Foundations; CSS :root locked token block"
	},
	"sp-12": {
		"key": "sp-12",
		"value": "40px",
		"cssVariable": "--sp-12",
		"role": "section gap (tight)",
		"source": "section 22 — Foundations; CSS :root locked token block"
	},
	"sp-13": {
		"key": "sp-13",
		"value": "56px",
		"cssVariable": "--sp-13",
		"role": "section padding-y",
		"source": "section 22 — Foundations; CSS :root locked token block"
	},
	"sp-14": {
		"key": "sp-14",
		"value": "80px",
		"cssVariable": "--sp-14",
		"role": "=== Border-radius scale ===",
		"source": "section 22 — Foundations; CSS :root locked token block"
	}
} as const satisfies Record<string, TokenEntry>;

export const radiusTokens = {
	"r-1": {
		"key": "r-1",
		"value": "3px",
		"cssVariable": "--r-1",
		"role": "chips, count badges",
		"source": "section 22 — Foundations; CSS :root locked token block"
	},
	"r-2": {
		"key": "r-2",
		"value": "4px",
		"cssVariable": "--r-2",
		"role": "pills, citations",
		"source": "section 22 — Foundations; CSS :root locked token block"
	},
	"r-3": {
		"key": "r-3",
		"value": "5px",
		"cssVariable": "--r-3",
		"role": "small buttons",
		"source": "section 22 — Foundations; CSS :root locked token block"
	},
	"r-4": {
		"key": "r-4",
		"value": "6px",
		"cssVariable": "--r-4",
		"role": "default buttons, inputs",
		"source": "section 22 — Foundations; CSS :root locked token block"
	},
	"r-5": {
		"key": "r-5",
		"value": "7px",
		"cssVariable": "--r-5",
		"role": "cards, panels",
		"source": "section 22 — Foundations; CSS :root locked token block"
	},
	"r-6": {
		"key": "r-6",
		"value": "8px",
		"cssVariable": "--r-6",
		"role": "dashboards, modals",
		"source": "section 22 — Foundations; CSS :root locked token block"
	},
	"r-7": {
		"key": "r-7",
		"value": "10px",
		"cssVariable": "--r-7",
		"source": "section 22 — Foundations; CSS :root locked token block"
	},
	"r-full": {
		"key": "r-full",
		"value": "50%",
		"cssVariable": "--r-full",
		"role": "=== Motion ===",
		"source": "section 22 — Foundations; CSS :root locked token block"
	}
} as const satisfies Record<string, TokenEntry>;

export const motionTokens = {
	"motion-instant": {
		"key": "motion-instant",
		"value": "0ms",
		"cssVariable": "--motion-instant",
		"source": "section 22 — Foundations; CSS :root locked token block"
	},
	"motion-fast": {
		"key": "motion-fast",
		"value": "120ms",
		"cssVariable": "--motion-fast",
		"role": "hover, focus rings",
		"source": "section 22 — Foundations; CSS :root locked token block"
	},
	"motion-medium": {
		"key": "motion-medium",
		"value": "180ms",
		"cssVariable": "--motion-medium",
		"role": "tooltips, popovers",
		"source": "section 22 — Foundations; CSS :root locked token block"
	},
	"motion-slow": {
		"key": "motion-slow",
		"value": "240ms",
		"cssVariable": "--motion-slow",
		"role": "modals, side panels",
		"source": "section 22 — Foundations; CSS :root locked token block"
	},
	"motion-page": {
		"key": "motion-page",
		"value": "320ms",
		"cssVariable": "--motion-page",
		"role": "route transitions",
		"source": "section 22 — Foundations; CSS :root locked token block"
	},
	"ease-out": {
		"key": "ease-out",
		"value": "cubic-bezier(0.2, 0.8, 0.2, 1)",
		"cssVariable": "--ease-out",
		"role": "cubic-bezier(0.16, 1, 0.3, 1)",
		"source": "section 22 — Foundations; CSS :root locked token block"
	},
	"ease-in": {
		"key": "ease-in",
		"value": "cubic-bezier(0.4, 0, 0.6, 0.4)",
		"cssVariable": "--ease-in",
		"source": "section 22 — Foundations; CSS :root locked token block"
	},
	"ease-in-out": {
		"key": "ease-in-out",
		"value": "cubic-bezier(0.4, 0, 0.2, 1)",
		"cssVariable": "--ease-in-out",
		"role": "cubic-bezier(0.4, 0, 0.2, 1)",
		"source": "section 22 — Foundations; CSS :root locked token block"
	},
	"ease-spring": {
		"key": "ease-spring",
		"value": "cubic-bezier(0.16, 1, 0.3, 1)",
		"cssVariable": "--ease-spring",
		"role": "=== Shadows ===",
		"source": "section 22 — Foundations; CSS :root locked token block"
	},
	"loop-qring": {
		"key": "loop-qring",
		"value": "0.9s linear infinite",
		"role": "quarter-ring loader rotation; outside named --motion-* tokens (loop, not transition)",
		"source": "section 63 — Loading micro-indicators",
		"name": "qring rotation (Section 63)"
	},
	"loop-dring": {
		"key": "loop-dring",
		"value": "1.2s linear infinite",
		"role": "dash-ring sync indicator rotation; outside named --motion-* tokens",
		"source": "section 63 — Loading micro-indicators",
		"name": "dring rotation (Section 63)"
	},
	"loop-bars": {
		"key": "loop-bars",
		"value": "0.95s ease-in-out infinite (0.13s stagger between)",
		"role": "analyzing/processing bars height pulse",
		"source": "section 63 — Loading micro-indicators",
		"name": "bars amplitude (Section 63)"
	},
	"loop-shimmer": {
		"key": "loop-shimmer",
		"value": "1.6s ease-in-out infinite",
		"role": "streaming-token gradient sweep on actively-streaming line",
		"source": "section 63 — Loading micro-indicators",
		"name": "text shimmer (Section 63)"
	},
	"loop-cursor": {
		"key": "loop-cursor",
		"value": "1.06s steps(1, end) infinite",
		"role": "log/terminal cursor blink (hard on/off, no fade)",
		"source": "section 63 — Loading micro-indicators",
		"name": "terminal cursor (Section 63)"
	},
	"loop-active-pulse": {
		"key": "loop-active-pulse",
		"value": "1.8s ease-in-out infinite",
		"role": "approval workflow active step ring pulse; signals 'your turn'",
		"source": "section 59 — Approval workflow (P-14 motion)",
		"name": "active step pulse (Section 59 P-14)"
	},
	"anim-check-draw": {
		"key": "anim-check-draw",
		"value": "0.75s ease-out forwards",
		"role": "approval workflow done step check-mark draw on transition; one-shot",
		"source": "section 59 — Approval workflow (P-14 motion)",
		"name": "check-draw transition (Section 59 P-14)"
	}
} as const satisfies Record<string, TokenEntry>;

export const typographyTokens = {
	"headline-display": {
		"key": "headline-display",
		"value": "Inter 700 · 44px / 1.1 / -0.03em",
		"source": "section 05 — Typography",
		"name": ".headline-display"
	},
	"heading-h1": {
		"key": "heading-h1",
		"value": "Inter 600 · 32px / 1.2 / -0.02em",
		"source": "section 05 — Typography",
		"name": ".heading-h1"
	},
	"heading-h2": {
		"key": "heading-h2",
		"value": "Inter 600 · 22px / 1.3 / 0",
		"source": "section 05 — Typography",
		"name": ".heading-h2"
	},
	"body": {
		"key": "body",
		"value": "default body, descriptions",
		"source": "section 05 — Typography",
		"name": "Body"
	},
	"text-small": {
		"key": "text-small",
		"value": "Inter 400 · 13px / 1.5 / 0",
		"source": "section 05 — Typography",
		"name": ".text-small"
	},
	"text-mono": {
		"key": "text-mono",
		"value": "JetBrains Mono 500 · 12px / 1.5 / 0.04em",
		"source": "section 05 — Typography",
		"name": ".text-mono"
	},
	"font-sans": {
		"key": "font-sans",
		"value": "\"Inter\", system-ui, sans-serif",
		"source": "section 05 — Typography",
		"name": "--font-sans"
	},
	"font-mono": {
		"key": "font-mono",
		"value": "\"JetBrains Mono\", monospace",
		"source": "section 05 — Typography",
		"name": "--font-mono"
	},
	"loaded-weights-inter": {
		"key": "loaded-weights-inter",
		"value": "300, 400, 500, 600, 700",
		"source": "section 05 — Typography",
		"name": "loaded weights (Inter)"
	},
	"loaded-weights-mono": {
		"key": "loaded-weights-mono",
		"value": "400, 500",
		"source": "section 05 — Typography",
		"name": "loaded weights (mono)"
	},
	"font-source": {
		"key": "font-source",
		"value": "Google Fonts (free)",
		"source": "section 05 — Typography",
		"name": "font source"
	},
	"display": {
		"key": "display",
		"value": "marketing hero, lockup taglines",
		"source": "section 05 — Typography",
		"name": "Display"
	},
	"h1": {
		"key": "h1",
		"value": "page title, section opener",
		"source": "section 05 — Typography",
		"name": "H1"
	},
	"h2-body": {
		"key": "h2-body",
		"value": "0 (default)",
		"source": "section 05 — Typography",
		"name": "h2 / body"
	},
	"mono": {
		"key": "mono",
		"value": "IDs, citations, timestamps, code, kbd",
		"source": "section 05 — Typography",
		"name": "Mono"
	},
	"eyebrow-caps": {
		"key": "eyebrow-caps",
		"value": "+0.10em (uppercase)",
		"source": "section 05 — Typography",
		"name": "eyebrow caps"
	},
	"nav-labels-caps": {
		"key": "nav-labels-caps",
		"value": "+0.14em (uppercase)",
		"source": "section 05 — Typography",
		"name": "nav labels caps"
	},
	"h2": {
		"key": "h2",
		"value": "subsection, card title",
		"source": "section 05 — Typography",
		"name": "H2"
	},
	"small": {
		"key": "small",
		"value": "meta, captions, helper",
		"source": "section 05 — Typography",
		"name": "Small"
	},
	"min-body-size": {
		"key": "min-body-size",
		"value": "13px (Small) — never below",
		"source": "section 05 — Typography",
		"name": "min body size"
	},
	"min-line-height": {
		"key": "min-line-height",
		"value": "1.5 (body); 1.2 acceptable for display",
		"source": "section 05 — Typography",
		"name": "min line-height"
	},
	"dynamic-type": {
		"key": "dynamic-type",
		"value": "all sizes scale with rem",
		"source": "section 05 — Typography",
		"name": "dynamic type"
	},
	"font-display": {
		"key": "font-display",
		"value": "swap (no FOIT)",
		"source": "section 05 — Typography",
		"name": "font-display"
	},
	"dyslexia-safe": {
		"key": "dyslexia-safe",
		"value": "Inter passes; avoid all-italic body",
		"source": "section 05 — Typography",
		"name": "dyslexia-safe"
	},
	"scale-base": {
		"key": "scale-base",
		"value": "16px (1rem) body",
		"source": "section 05 — Typography",
		"name": "scale base"
	}
} as const satisfies Record<string, TokenEntry>;

export const shadowTokens = {
	"shadow-card-dark": {
		"key": "shadow-card-dark",
		"value": "0 1px 0 rgba(255,255,255,0.05) inset, 0 1px 4px rgba(0,0,0,0.4)",
		"cssVariable": "--shadow-card-dark",
		"source": "section 22 — Foundations; CSS :root locked token block"
	},
	"shadow-card-light": {
		"key": "shadow-card-light",
		"value": "0 1px 0 rgba(255,255,255,0.6) inset, 0 1px 3px rgba(31,29,26,0.05)",
		"cssVariable": "--shadow-card-light",
		"source": "section 22 — Foundations; CSS :root locked token block"
	},
	"shadow-modal-dark": {
		"key": "shadow-modal-dark",
		"value": "0 1px 0 rgba(255,255,255,0.06) inset, 0 16px 48px rgba(0,0,0,0.6)",
		"cssVariable": "--shadow-modal-dark",
		"source": "section 22 — Foundations; CSS :root locked token block"
	},
	"shadow-modal-light": {
		"key": "shadow-modal-light",
		"value": "0 1px 0 rgba(255,255,255,0.7) inset, 0 16px 48px rgba(31,29,26,0.18)",
		"cssVariable": "--shadow-modal-light",
		"source": "section 22 — Foundations; CSS :root locked token block"
	},
	"shadow-tooltip-dark": {
		"key": "shadow-tooltip-dark",
		"value": "0 12px 32px rgba(0,0,0,0.5)",
		"cssVariable": "--shadow-tooltip-dark",
		"source": "section 22 — Foundations; CSS :root locked token block"
	},
	"shadow-tooltip-light": {
		"key": "shadow-tooltip-light",
		"value": "0 12px 32px rgba(31,29,26,0.15)",
		"cssVariable": "--shadow-tooltip-light",
		"role": "=== Focus ring ===",
		"source": "section 22 — Foundations; CSS :root locked token block"
	}
} as const satisfies Record<string, TokenEntry>;

export const focusTokens = {
	"focus-ring": {
		"key": "focus-ring",
		"value": "0 0 0 3px rgba(160, 88, 71, 0.5)",
		"cssVariable": "--focus-ring",
		"role": "clay-tinted, 50% opacity",
		"source": "section 22 — Foundations; CSS :root locked token block"
	},
	"focus-ring-soft": {
		"key": "focus-ring-soft",
		"value": "0 0 0 3px rgba(160, 88, 71, 0.18)",
		"cssVariable": "--focus-ring-soft",
		"role": "=== Responsive breakpoints (referenced via @media; documented for consistency) ===",
		"source": "section 22 — Foundations; CSS :root locked token block"
	}
} as const satisfies Record<string, TokenEntry>;

export const breakpointTokens = {
	"bp-mobile": {
		"key": "bp-mobile",
		"value": "640px",
		"cssVariable": "--bp-mobile",
		"role": "responsive breakpoint",
		"source": "section 22 — Foundations"
	},
	"bp-tablet": {
		"key": "bp-tablet",
		"value": "1024px",
		"cssVariable": "--bp-tablet",
		"role": "responsive breakpoint",
		"source": "section 22 — Foundations"
	},
	"bp-desktop": {
		"key": "bp-desktop",
		"value": "1440px",
		"cssVariable": "--bp-desktop",
		"role": "responsive breakpoint",
		"source": "section 22 — Foundations"
	},
	"bp-wide": {
		"key": "bp-wide",
		"value": "1920px",
		"cssVariable": "--bp-wide",
		"role": "responsive breakpoint",
		"source": "section 22 — Foundations"
	}
} as const satisfies Record<string, TokenEntry>;

export const brandMarkTokens = {
	"bk-v-margin-right": {
		"key": "bk-v-margin-right",
		"value": "-0.07em",
		"cssVariable": "--bk-v-margin-right",
		"role": "V-to-e gap — tightened from -0.05em",
		"source": "section 01 — Wordmark; CSS :root locked token block"
	},
	"bk-dot-size": {
		"key": "bk-dot-size",
		"value": "0.18em",
		"cssVariable": "--bk-dot-size",
		"role": "dot diameter relative to wordmark font-size",
		"source": "section 01 — Wordmark; CSS :root locked token block"
	},
	"bk-dot-margin-left": {
		"key": "bk-dot-margin-left",
		"value": "0.04em",
		"cssVariable": "--bk-dot-margin-left",
		"role": "spacing from \"l\" — bumped from 0.02em for breathing room",
		"source": "section 01 — Wordmark; CSS :root locked token block"
	},
	"bk-dot-margin-bottom": {
		"key": "bk-dot-margin-bottom",
		"value": "0.005em",
		"cssVariable": "--bk-dot-margin-bottom",
		"role": "baseline-sit nudge",
		"source": "section 01 — Wordmark; CSS :root locked token block"
	}
} as const satisfies Record<string, TokenEntry>;

export const lockedRootVariables = [
	{
		"key": "bg-app-light",
		"value": "#FAFAF8",
		"cssVariable": "--bg-app-light",
		"source": "CSS :root locked token block, lines 12-104",
		"category": "colors"
	},
	{
		"key": "bg-card-light",
		"value": "#FFFFFF",
		"cssVariable": "--bg-card-light",
		"source": "CSS :root locked token block, lines 12-104",
		"category": "colors"
	},
	{
		"key": "bg-card-light-bottom",
		"value": "#FBFAF7",
		"cssVariable": "--bg-card-light-bottom",
		"source": "CSS :root locked token block, lines 12-104",
		"description": "card gradient bottom on light",
		"category": "colors"
	},
	{
		"key": "bg-soft-light",
		"value": "#F4F4F1",
		"cssVariable": "--bg-soft-light",
		"source": "CSS :root locked token block, lines 12-104",
		"category": "colors"
	},
	{
		"key": "bg-hover-light",
		"value": "#EFEFEC",
		"cssVariable": "--bg-hover-light",
		"source": "CSS :root locked token block, lines 12-104",
		"category": "colors"
	},
	{
		"key": "border-light",
		"value": "#E8E6E0",
		"cssVariable": "--border-light",
		"source": "CSS :root locked token block, lines 12-104",
		"category": "colors"
	},
	{
		"key": "border-light-subtle",
		"value": "#F0EEE8",
		"cssVariable": "--border-light-subtle",
		"source": "CSS :root locked token block, lines 12-104",
		"category": "colors"
	},
	{
		"key": "border-light-strong",
		"value": "#D6D3CB",
		"cssVariable": "--border-light-strong",
		"source": "CSS :root locked token block, lines 12-104",
		"description": "=== Surfaces (dark) ===",
		"category": "colors"
	},
	{
		"key": "bg-sidebar-dark",
		"value": "#0a0b0d",
		"cssVariable": "--bg-sidebar-dark",
		"source": "CSS :root locked token block, lines 12-104",
		"description": "always-dark sidebar (both modes)",
		"category": "colors"
	},
	{
		"key": "bg-app-dark",
		"value": "#131517",
		"cssVariable": "--bg-app-dark",
		"source": "CSS :root locked token block, lines 12-104",
		"description": "main bg / app surface (dark mode)",
		"category": "colors"
	},
	{
		"key": "bg-card-dark-top",
		"value": "#21242a",
		"cssVariable": "--bg-card-dark-top",
		"source": "CSS :root locked token block, lines 12-104",
		"description": "card gradient top",
		"category": "colors"
	},
	{
		"key": "bg-card-dark-bottom",
		"value": "#1c1e23",
		"cssVariable": "--bg-card-dark-bottom",
		"source": "CSS :root locked token block, lines 12-104",
		"description": "card gradient bottom",
		"category": "colors"
	},
	{
		"key": "bg-pill-dark",
		"value": "#1f2126",
		"cssVariable": "--bg-pill-dark",
		"source": "CSS :root locked token block, lines 12-104",
		"description": "topbar pill, secondary surfaces",
		"category": "colors"
	},
	{
		"key": "bg-cta-dark",
		"value": "#1F1D1A",
		"cssVariable": "--bg-cta-dark",
		"source": "CSS :root locked token block, lines 12-104",
		"description": "primary CTA bubble (warm black, locked)",
		"category": "colors"
	},
	{
		"key": "border-dark",
		"value": "#2d2f36",
		"cssVariable": "--border-dark",
		"source": "CSS :root locked token block, lines 12-104",
		"description": "card borders, subtle dividers",
		"category": "colors"
	},
	{
		"key": "border-dark-subtle",
		"value": "#1d1f24",
		"cssVariable": "--border-dark-subtle",
		"source": "CSS :root locked token block, lines 12-104",
		"description": "deepest separators",
		"category": "colors"
	},
	{
		"key": "text-light-primary",
		"value": "#1F1D1A",
		"cssVariable": "--text-light-primary",
		"source": "CSS :root locked token block, lines 12-104",
		"description": "headings, body emphasis",
		"category": "colors"
	},
	{
		"key": "text-light-secondary",
		"value": "#5A5550",
		"cssVariable": "--text-light-secondary",
		"source": "CSS :root locked token block, lines 12-104",
		"description": "body text",
		"category": "colors"
	},
	{
		"key": "text-light-tertiary",
		"value": "#918A82",
		"cssVariable": "--text-light-tertiary",
		"source": "CSS :root locked token block, lines 12-104",
		"description": "meta, timestamps",
		"category": "colors"
	},
	{
		"key": "text-light-disabled",
		"value": "#B8B2A8",
		"cssVariable": "--text-light-disabled",
		"source": "CSS :root locked token block, lines 12-104",
		"description": "dividers, separator chars",
		"category": "colors"
	},
	{
		"key": "text-dark-primary",
		"value": "#f7f8f8",
		"cssVariable": "--text-dark-primary",
		"source": "CSS :root locked token block, lines 12-104",
		"description": "LOCKED soft off-white. Headings, eyebrow flagged, wordmark.",
		"category": "colors"
	},
	{
		"key": "text-dark-body",
		"value": "#d0d6e0",
		"cssVariable": "--text-dark-body",
		"source": "CSS :root locked token block, lines 12-104",
		"description": "body text, action row titles",
		"category": "colors"
	},
	{
		"key": "text-dark-muted",
		"value": "#9097a1",
		"cssVariable": "--text-dark-muted",
		"source": "CSS :root locked token block, lines 12-104",
		"description": "eyebrow type label, action row details",
		"category": "colors"
	},
	{
		"key": "text-dark-tertiary",
		"value": "#62666d",
		"cssVariable": "--text-dark-tertiary",
		"source": "CSS :root locked token block, lines 12-104",
		"description": "section labels, meta, dividers",
		"category": "colors"
	},
	{
		"key": "text-dark-disabled",
		"value": "#5a5e66",
		"cssVariable": "--text-dark-disabled",
		"source": "CSS :root locked token block, lines 12-104",
		"description": "disabled buttons, placeholder",
		"category": "colors"
	},
	{
		"key": "clay-light",
		"value": "#A05847",
		"cssVariable": "--clay-light",
		"source": "CSS :root locked token block, lines 12-104",
		"description": "LOCKED primary on light surfaces (wordmark, references, chrome)",
		"category": "colors"
	},
	{
		"key": "clay-bright",
		"value": "#C68070",
		"cssVariable": "--clay-bright",
		"source": "CSS :root locked token block, lines 12-104",
		"description": "LOCKED primary on dark surfaces",
		"category": "colors"
	},
	{
		"key": "clay",
		"value": "#7A3D32",
		"cssVariable": "--clay",
		"source": "CSS :root locked token block, lines 12-104",
		"description": "deep brand accent for high-emphasis",
		"category": "colors"
	},
	{
		"key": "clay-dark",
		"value": "#5C2D26",
		"cssVariable": "--clay-dark",
		"source": "CSS :root locked token block, lines 12-104",
		"description": "hover/depth for clay-family",
		"category": "colors"
	},
	{
		"key": "success",
		"value": "#5DA17D",
		"cssVariable": "--success",
		"source": "CSS :root locked token block, lines 12-104",
		"description": "live indicator, confidence high, success states",
		"category": "colors"
	},
	{
		"key": "success-dark",
		"value": "#4a8a68",
		"cssVariable": "--success-dark",
		"source": "CSS :root locked token block, lines 12-104",
		"description": "gradient toned-down variant",
		"category": "colors"
	},
	{
		"key": "warning-light",
		"value": "#A87A2E",
		"cssVariable": "--warning-light",
		"source": "CSS :root locked token block, lines 12-104",
		"description": "flagged status on light surface",
		"category": "colors"
	},
	{
		"key": "warning-dark",
		"value": "#d4a960",
		"cssVariable": "--warning-dark",
		"source": "CSS :root locked token block, lines 12-104",
		"description": "flagged status on dark surface",
		"category": "colors"
	},
	{
		"key": "error",
		"value": "#c95151",
		"cssVariable": "--error",
		"source": "CSS :root locked token block, lines 12-104",
		"description": "high priority, overdue, error states",
		"category": "colors"
	},
	{
		"key": "error-dark",
		"value": "#B53D3D",
		"cssVariable": "--error-dark",
		"source": "CSS :root locked token block, lines 12-104",
		"description": "darker error for emphasis",
		"category": "colors"
	},
	{
		"key": "info",
		"value": "#5A6878",
		"cssVariable": "--info",
		"source": "CSS :root locked token block, lines 12-104",
		"description": "muted slate for info banners",
		"category": "colors"
	},
	{
		"key": "sp-0",
		"value": "0px",
		"cssVariable": "--sp-0",
		"source": "CSS :root locked token block, lines 12-104",
		"category": "spacing"
	},
	{
		"key": "sp-1",
		"value": "2px",
		"cssVariable": "--sp-1",
		"source": "CSS :root locked token block, lines 12-104",
		"category": "spacing"
	},
	{
		"key": "sp-2",
		"value": "4px",
		"cssVariable": "--sp-2",
		"source": "CSS :root locked token block, lines 12-104",
		"category": "spacing"
	},
	{
		"key": "sp-3",
		"value": "6px",
		"cssVariable": "--sp-3",
		"source": "CSS :root locked token block, lines 12-104",
		"category": "spacing"
	},
	{
		"key": "sp-4",
		"value": "8px",
		"cssVariable": "--sp-4",
		"source": "CSS :root locked token block, lines 12-104",
		"category": "spacing"
	},
	{
		"key": "sp-5",
		"value": "10px",
		"cssVariable": "--sp-5",
		"source": "CSS :root locked token block, lines 12-104",
		"category": "spacing"
	},
	{
		"key": "sp-6",
		"value": "12px",
		"cssVariable": "--sp-6",
		"source": "CSS :root locked token block, lines 12-104",
		"category": "spacing"
	},
	{
		"key": "sp-7",
		"value": "14px",
		"cssVariable": "--sp-7",
		"source": "CSS :root locked token block, lines 12-104",
		"category": "spacing"
	},
	{
		"key": "sp-8",
		"value": "16px",
		"cssVariable": "--sp-8",
		"source": "CSS :root locked token block, lines 12-104",
		"category": "spacing"
	},
	{
		"key": "sp-9",
		"value": "20px",
		"cssVariable": "--sp-9",
		"source": "CSS :root locked token block, lines 12-104",
		"category": "spacing"
	},
	{
		"key": "sp-10",
		"value": "24px",
		"cssVariable": "--sp-10",
		"source": "CSS :root locked token block, lines 12-104",
		"category": "spacing"
	},
	{
		"key": "sp-11",
		"value": "32px",
		"cssVariable": "--sp-11",
		"source": "CSS :root locked token block, lines 12-104",
		"category": "spacing"
	},
	{
		"key": "sp-12",
		"value": "40px",
		"cssVariable": "--sp-12",
		"source": "CSS :root locked token block, lines 12-104",
		"category": "spacing"
	},
	{
		"key": "sp-13",
		"value": "56px",
		"cssVariable": "--sp-13",
		"source": "CSS :root locked token block, lines 12-104",
		"category": "spacing"
	},
	{
		"key": "sp-14",
		"value": "80px",
		"cssVariable": "--sp-14",
		"source": "CSS :root locked token block, lines 12-104",
		"description": "=== Border-radius scale ===",
		"category": "spacing"
	},
	{
		"key": "r-1",
		"value": "3px",
		"cssVariable": "--r-1",
		"source": "CSS :root locked token block, lines 12-104",
		"category": "radii"
	},
	{
		"key": "r-2",
		"value": "4px",
		"cssVariable": "--r-2",
		"source": "CSS :root locked token block, lines 12-104",
		"category": "radii"
	},
	{
		"key": "r-3",
		"value": "5px",
		"cssVariable": "--r-3",
		"source": "CSS :root locked token block, lines 12-104",
		"category": "radii"
	},
	{
		"key": "r-4",
		"value": "6px",
		"cssVariable": "--r-4",
		"source": "CSS :root locked token block, lines 12-104",
		"category": "radii"
	},
	{
		"key": "r-5",
		"value": "7px",
		"cssVariable": "--r-5",
		"source": "CSS :root locked token block, lines 12-104",
		"category": "radii"
	},
	{
		"key": "r-6",
		"value": "8px",
		"cssVariable": "--r-6",
		"source": "CSS :root locked token block, lines 12-104",
		"category": "radii"
	},
	{
		"key": "r-7",
		"value": "10px",
		"cssVariable": "--r-7",
		"source": "CSS :root locked token block, lines 12-104",
		"category": "radii"
	},
	{
		"key": "r-full",
		"value": "50%",
		"cssVariable": "--r-full",
		"source": "CSS :root locked token block, lines 12-104",
		"description": "=== Motion ===",
		"category": "radii"
	},
	{
		"key": "motion-instant",
		"value": "0ms",
		"cssVariable": "--motion-instant",
		"source": "CSS :root locked token block, lines 12-104",
		"category": "motion"
	},
	{
		"key": "motion-fast",
		"value": "120ms",
		"cssVariable": "--motion-fast",
		"source": "CSS :root locked token block, lines 12-104",
		"description": "hover, focus rings",
		"category": "motion"
	},
	{
		"key": "motion-medium",
		"value": "180ms",
		"cssVariable": "--motion-medium",
		"source": "CSS :root locked token block, lines 12-104",
		"description": "tooltips, popovers",
		"category": "motion"
	},
	{
		"key": "motion-slow",
		"value": "240ms",
		"cssVariable": "--motion-slow",
		"source": "CSS :root locked token block, lines 12-104",
		"description": "modals, side panels",
		"category": "motion"
	},
	{
		"key": "motion-page",
		"value": "320ms",
		"cssVariable": "--motion-page",
		"source": "CSS :root locked token block, lines 12-104",
		"description": "route transitions",
		"category": "motion"
	},
	{
		"key": "ease-out",
		"value": "cubic-bezier(0.2, 0.8, 0.2, 1)",
		"cssVariable": "--ease-out",
		"source": "CSS :root locked token block, lines 12-104",
		"category": "motion"
	},
	{
		"key": "ease-in",
		"value": "cubic-bezier(0.4, 0, 0.6, 0.4)",
		"cssVariable": "--ease-in",
		"source": "CSS :root locked token block, lines 12-104",
		"category": "motion"
	},
	{
		"key": "ease-in-out",
		"value": "cubic-bezier(0.4, 0, 0.2, 1)",
		"cssVariable": "--ease-in-out",
		"source": "CSS :root locked token block, lines 12-104",
		"category": "motion"
	},
	{
		"key": "ease-spring",
		"value": "cubic-bezier(0.16, 1, 0.3, 1)",
		"cssVariable": "--ease-spring",
		"source": "CSS :root locked token block, lines 12-104",
		"description": "=== Shadows ===",
		"category": "motion"
	},
	{
		"key": "shadow-card-dark",
		"value": "0 1px 0 rgba(255,255,255,0.05) inset, 0 1px 4px rgba(0,0,0,0.4)",
		"cssVariable": "--shadow-card-dark",
		"source": "CSS :root locked token block, lines 12-104",
		"category": "shadows"
	},
	{
		"key": "shadow-card-light",
		"value": "0 1px 0 rgba(255,255,255,0.6) inset, 0 1px 3px rgba(31,29,26,0.05)",
		"cssVariable": "--shadow-card-light",
		"source": "CSS :root locked token block, lines 12-104",
		"category": "shadows"
	},
	{
		"key": "shadow-modal-dark",
		"value": "0 1px 0 rgba(255,255,255,0.06) inset, 0 16px 48px rgba(0,0,0,0.6)",
		"cssVariable": "--shadow-modal-dark",
		"source": "CSS :root locked token block, lines 12-104",
		"category": "shadows"
	},
	{
		"key": "shadow-modal-light",
		"value": "0 1px 0 rgba(255,255,255,0.7) inset, 0 16px 48px rgba(31,29,26,0.18)",
		"cssVariable": "--shadow-modal-light",
		"source": "CSS :root locked token block, lines 12-104",
		"category": "shadows"
	},
	{
		"key": "shadow-tooltip-dark",
		"value": "0 12px 32px rgba(0,0,0,0.5)",
		"cssVariable": "--shadow-tooltip-dark",
		"source": "CSS :root locked token block, lines 12-104",
		"category": "shadows"
	},
	{
		"key": "shadow-tooltip-light",
		"value": "0 12px 32px rgba(31,29,26,0.15)",
		"cssVariable": "--shadow-tooltip-light",
		"source": "CSS :root locked token block, lines 12-104",
		"description": "=== Focus ring ===",
		"category": "shadows"
	},
	{
		"key": "focus-ring",
		"value": "0 0 0 3px rgba(160, 88, 71, 0.5)",
		"cssVariable": "--focus-ring",
		"source": "CSS :root locked token block, lines 12-104",
		"description": "clay-tinted, 50% opacity",
		"category": "focus"
	},
	{
		"key": "focus-ring-soft",
		"value": "0 0 0 3px rgba(160, 88, 71, 0.18)",
		"cssVariable": "--focus-ring-soft",
		"source": "CSS :root locked token block, lines 12-104",
		"description": "=== Responsive breakpoints (referenced via @media; documented for consistency) ===",
		"category": "focus"
	},
	{
		"key": "bp-mobile",
		"value": "640px",
		"cssVariable": "--bp-mobile",
		"source": "CSS :root locked token block, lines 12-104",
		"category": "other"
	},
	{
		"key": "bp-tablet",
		"value": "1024px",
		"cssVariable": "--bp-tablet",
		"source": "CSS :root locked token block, lines 12-104",
		"category": "other"
	},
	{
		"key": "bp-desktop",
		"value": "1440px",
		"cssVariable": "--bp-desktop",
		"source": "CSS :root locked token block, lines 12-104",
		"category": "other"
	},
	{
		"key": "bp-wide",
		"value": "1920px",
		"cssVariable": "--bp-wide",
		"source": "CSS :root locked token block, lines 12-104",
		"category": "other"
	},
	{
		"key": "bk-v-margin-right",
		"value": "-0.07em",
		"cssVariable": "--bk-v-margin-right",
		"source": "CSS :root locked token block, lines 12-104",
		"description": "V-to-e gap — tightened from -0.05em",
		"category": "brandMark"
	},
	{
		"key": "bk-dot-size",
		"value": "0.18em",
		"cssVariable": "--bk-dot-size",
		"source": "CSS :root locked token block, lines 12-104",
		"description": "dot diameter relative to wordmark font-size",
		"category": "brandMark"
	},
	{
		"key": "bk-dot-margin-left",
		"value": "0.04em",
		"cssVariable": "--bk-dot-margin-left",
		"source": "CSS :root locked token block, lines 12-104",
		"description": "spacing from \"l\" — bumped from 0.02em for breathing room",
		"category": "brandMark"
	},
	{
		"key": "bk-dot-margin-bottom",
		"value": "0.005em",
		"cssVariable": "--bk-dot-margin-bottom",
		"source": "CSS :root locked token block, lines 12-104",
		"description": "baseline-sit nudge",
		"category": "brandMark"
	}
] as const satisfies readonly TokenEntry[];

export const vecrealTokens = {
	meta: tokenMetadata,
	colors: colorTokens,
	spacing: spacingTokens,
	radii: radiusTokens,
	motion: motionTokens,
	typography: typographyTokens,
	shadows: shadowTokens,
	focus: focusTokens,
	breakpoints: breakpointTokens,
	brandMark: brandMarkTokens,
	lockedRootVariables,
} as const;

export type VecrealTokens = typeof vecrealTokens;
